In [1]:
import torch

In [2]:
mat = torch.rand((3,3))
print(mat)

mat2 = torch.zeros((3,3))
print(mat2)

mat3 = mat + mat2
print(mat3)

vector = mat3.reshape(1,-1)
print(vector)

maxim = torch.max(vector)
print(maxim)

tensor([[0.0861, 0.4023, 0.2880],
        [0.2720, 0.1297, 0.9665],
        [0.3139, 0.6295, 0.9025]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0861, 0.4023, 0.2880],
        [0.2720, 0.1297, 0.9665],
        [0.3139, 0.6295, 0.9025]])
tensor([[0.0861, 0.4023, 0.2880, 0.2720, 0.1297, 0.9665, 0.3139, 0.6295, 0.9025]])
tensor(0.9665)


In [3]:
# 1. Crea un tensore con requires_grad=True
x = torch.rand(1, requires_grad=True)
print(x)

# 2. Costruisci la funzione: y = x^2 + 3x + 2
y = x**2 + 3*x + 2
z = 1*x

# 3. Calcola il gradiente di y rispetto a x
y.backward()
z.backward()
print(x.grad)


tensor([0.5545], requires_grad=True)
tensor([5.1090])


In [25]:
import torch

n = 100
d = 5
itera = 1000
lr = 0.001

x = torch.rand((n, d))
beta = 100*torch.randn((d, 1))                    # Coefficienti veri non nulli
noise = 0.1 * torch.randn((n, 1))             # Rumore piccolo, media zero
y = x @ beta + noise

betahat = torch.zeros((d, 1), requires_grad=True)
optimizer = torch.optim.SGD([betahat], lr=lr)

for i in range(itera):
    optimizer.zero_grad()
    loss = torch.sum((y - x @ betahat) ** 2)

    loss.backward()
    optimizer.step()

print("Betahat:\n", betahat)
print("Beta (vero):\n", beta)

Betahat:
 tensor([[171.8245],
        [-14.6873],
        [-23.2674],
        [ 32.7727],
        [ 50.9832]], requires_grad=True)
Beta (vero):
 tensor([[171.8454],
        [-14.6993],
        [-23.2605],
        [ 32.7477],
        [ 50.9992]])


In [14]:
import torch.nn as nn

In [26]:
class SimpleNN(nn.Module):
    def __init__(self, input_dim, hidden_dim=10, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
    
    def forward(self, x):
        mid = torch.relu(self.fc1(x))
        return self.fc2(mid)
    
model = SimpleNN(d)

In [27]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.05)

In [28]:
for i in range(itera):
    optimizer.zero_grad()
    y_pred = model(x)
    loss = criterion(y, y_pred)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if i % 10 == 0:
        print(f"Epoch {i}: Loss = {loss.item():.4f}")

Epoch 0: Loss = 13258.4902
Epoch 10: Loss = 11762.6416
Epoch 20: Loss = 8398.1084
Epoch 30: Loss = 4449.5791
Epoch 40: Loss = 2779.4988
Epoch 50: Loss = 2803.0752
Epoch 60: Loss = 2337.8511
Epoch 70: Loss = 2109.2827
Epoch 80: Loss = 1853.8573
Epoch 90: Loss = 1609.6769
Epoch 100: Loss = 1369.3868
Epoch 110: Loss = 1133.9597
Epoch 120: Loss = 908.9283
Epoch 130: Loss = 700.8144
Epoch 140: Loss = 518.2951
Epoch 150: Loss = 368.4298
Epoch 160: Loss = 254.7660
Epoch 170: Loss = 175.6570
Epoch 180: Loss = 124.9718
Epoch 190: Loss = 92.8257
Epoch 200: Loss = 71.7219
Epoch 210: Loss = 57.2134
Epoch 220: Loss = 46.6869
Epoch 230: Loss = 38.7486
Epoch 240: Loss = 32.6295
Epoch 250: Loss = 27.6756
Epoch 260: Loss = 23.6809
Epoch 270: Loss = 20.3666
Epoch 280: Loss = 17.5681
Epoch 290: Loss = 15.1923
Epoch 300: Loss = 13.1732
Epoch 310: Loss = 11.4565
Epoch 320: Loss = 10.0007
Epoch 330: Loss = 8.7704
Epoch 340: Loss = 7.7389
Epoch 350: Loss = 6.8892
Epoch 360: Loss = 6.1853
Epoch 370: Loss = 5.