In [1]:
import torch

In [2]:
mat = torch.rand((3,3))
print(mat)

mat2 = torch.zeros((3,3))
print(mat2)

mat3 = mat + mat2
print(mat3)

vector = mat3.reshape(1,-1)
print(vector)

maxim = torch.max(vector)
print(maxim)

tensor([[0.1106, 0.5393, 0.1928],
        [0.5187, 0.8729, 0.2554],
        [0.1710, 0.9611, 0.9671]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1106, 0.5393, 0.1928],
        [0.5187, 0.8729, 0.2554],
        [0.1710, 0.9611, 0.9671]])
tensor([[0.1106, 0.5393, 0.1928, 0.5187, 0.8729, 0.2554, 0.1710, 0.9611, 0.9671]])
tensor(0.9671)


In [3]:
# 1. Crea un tensore con requires_grad=True
x = torch.rand(1, requires_grad=True)
print(x)

# 2. Costruisci la funzione: y = x^2 + 3x + 2
y = x**2 + 3*x + 2
z = 1*x

# 3. Calcola il gradiente di y rispetto a x
y.backward()
z.backward()
print(x.grad)


tensor([0.0931], requires_grad=True)
tensor([4.1862])


In [4]:
import torch

n = 100
d = 5
itera = 1000
lr = 0.001

x = torch.rand((n, d))
beta = 100*torch.randn((d, 1))                    # Coefficienti veri non nulli
noise = 0.1 * torch.randn((n, 1))             # Rumore piccolo, media zero
y = x @ beta + noise

betahat = torch.zeros((d, 1), requires_grad=True)
optimizer = torch.optim.SGD([betahat], lr=lr)

for i in range(itera):
    optimizer.zero_grad()
    loss = torch.sum((y - x @ betahat) ** 2)

    loss.backward()
    optimizer.step()

print("Betahat:\n", betahat)
print("Beta (vero):\n", beta)

Betahat:
 tensor([[-42.9197],
        [-62.3390],
        [ 69.4050],
        [ 63.7649],
        [120.6579]], requires_grad=True)
Beta (vero):
 tensor([[-42.8911],
        [-62.3627],
        [ 69.4430],
        [ 63.7584],
        [120.6446]])


In [5]:
import torch.nn as nn

In [6]:
class SimpleNN(nn.Module):
    def __init__(self, input_dim, hidden_dim=10, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
    
    def forward(self, x):
        mid = torch.relu(self.fc1(x))
        return self.fc2(mid)
    
model = SimpleNN(d)

In [7]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.05)

In [8]:
for i in range(itera):
    optimizer.zero_grad()
    y_pred = model(x)
    loss = criterion(y, y_pred)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if i % 10 == 0:
        print(f"Epoch {i}: Loss = {loss.item():.4f}")

Epoch 0: Loss = 8223.5215
Epoch 10: Loss = 7478.3735
Epoch 20: Loss = 5722.2271
Epoch 30: Loss = 3424.3037
Epoch 40: Loss = 2001.9698
Epoch 50: Loss = 1733.0077
Epoch 60: Loss = 1349.4918
Epoch 70: Loss = 991.8601
Epoch 80: Loss = 683.7454
Epoch 90: Loss = 430.5856
Epoch 100: Loss = 244.2715
Epoch 110: Loss = 126.2532
Epoch 120: Loss = 62.5772
Epoch 130: Loss = 31.8985
Epoch 140: Loss = 17.7884
Epoch 150: Loss = 10.9753
Epoch 160: Loss = 7.4229
Epoch 170: Loss = 5.2858
Epoch 180: Loss = 3.7787
Epoch 190: Loss = 2.6698
Epoch 200: Loss = 1.8675
Epoch 210: Loss = 1.3003
Epoch 220: Loss = 0.9044
Epoch 230: Loss = 0.6339
Epoch 240: Loss = 0.4473
Epoch 250: Loss = 0.3173
Epoch 260: Loss = 0.2266
Epoch 270: Loss = 0.1631
Epoch 280: Loss = 0.1186
Epoch 290: Loss = 0.0873
Epoch 300: Loss = 0.0650
Epoch 310: Loss = 0.0491
Epoch 320: Loss = 0.0376
Epoch 330: Loss = 0.0293
Epoch 340: Loss = 0.0232
Epoch 350: Loss = 0.0188
Epoch 360: Loss = 0.0155
Epoch 370: Loss = 0.0131
Epoch 380: Loss = 0.0113
E