In [1]:
import torch
import torch.nn as nn

In [2]:
class SimpleNN(nn.Module):
    def __init__(self, input_dim=2, hidden_size=10):
        self.layer1 = nn.Linear(input_dim, hidden_size)
        self.layer2 = nn.Linear(hidden_size, 1)
    
    def forward(self, x):
        return self.layer2(torch.relu(self.layer1(x)))

In [6]:
n = 10
d = 2
X = torch.randn((n,d))
beta = torch.tensor([1., 2.])
print(beta)

# Etichette binarie: 1 se il prodotto scalare è positivo, 0 altrimenti
y = (X @ beta > 0).float()

print(y)

print("X:\n", X)
print("y:\n", y)

tensor([1., 2.])
tensor([0., 1., 1., 0., 1., 1., 1., 0., 0., 0.])
X:
 tensor([[-0.8777, -0.9495],
        [ 1.5962,  0.1014],
        [ 0.9474,  0.7797],
        [ 0.9743, -0.5976],
        [-1.1408,  0.7222],
        [ 1.1063,  0.4661],
        [-0.6893,  0.8878],
        [-1.6760, -0.8968],
        [-1.3875, -1.0486],
        [-0.6696, -0.1858]])
y:
 tensor([0., 1., 1., 0., 1., 1., 1., 0., 0., 0.])
